# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: GuptaAgentPool

steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        ConnectedServiceName: '$(connectedservicename)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'techversantdotnet'
        location: 'eastus'
        csmFile: 'AppServiceTemplate/template.json'
        csmParametersFile: 'AppServiceTemplate/parameters.json'
   
   
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: DeploymentFiles'
      inputs:
        PathtoPublish: 'DeploymentFiles'
        ArtifactName: DeploymentFiles
